WIP: add new max channel size config option
lightningnetwork/lnd pull request #4567
Opened 2020-08-25 04:53 UTC by calvinrzachman

- let users specify their MAXIMUM WUMBO with new config option which sets the maximum channel size lnd will accept
- current implementation is a simple check by the fundingManager rather than anything to do with the ChannelAcceptor

TODO: config validation and test case(s), use https://github.com/lightningnetwork/lnd/pull/4429 as WUMBO guide.

QUESTION: Should this configurable maximum be above the old soft-limit or should we permit any value? If above soft limit only, ensure that this setting does not override wumbo channel enablement (ie: don't impose a cap that is lower than the old limit)

Addresses: https://github.com/lightningnetwork/lnd/issues/4557

#### Pull Request Checklist

- [ ] If this is your first time contributing, we recommend you read the [Code
  Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md)
- [ ] All changes are Go version 1.12 compliant
- [ ] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
- [ ] For new code: Code is accompanied by tests which exercise both
  the positive and negative (error paths) conditions (if applicable)
- [ ] For bug fixes: Code is accompanied by new tests which trigger
  the bug being fixed to prevent regressions
- [ ] Any new logging statements use an appropriate subsystem and
  logging level
- [ ] Code has been formatted with `go fmt`
- [ ] Protobuf files (`lnrpc/**/*.proto`) have been formatted with
  `make rpc-format` and compiled with `make rpc`
- [ ] For code and documentation: lines are wrapped at 80 characters
  (the tab character should be counted as 8 characters, not 4, as some IDEs do
  per default)
- [ ] Running `make check` does not fail any tests
- [ ] Running `go vet` does not report any issues
- [ ] Running `make lint` does not report any **new** issues that did not
  already exist
- [ ] All commits build properly and pass tests. Only in exceptional
  cases it can be justifiable to violate this condition. In that case, the
  reason should be stated in the commit message.
- [ ] Commits have a logical structure according to [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)

2020-08-25 22:44 UTC, Roasbeef commented on fundingmanager.go
> +	if f.cfg.NoWumboChans && amt > MaxFundingAmount {
👍

2020-08-25 22:48 UTC, Roasbeef commented
NP on not using a channel acceptor, this is much simpler after all, in the future we may opt to roll it out into one, just so we can have all the logic coupled in a single place. 

>  Should this configurable maximum be above the old soft-limit or should we permit any value? If above soft limit only, ensure that this setting does not override wumbo channel enablement (ie: don't impose a cap that is lower than the old limit)

What do you mean above the old soft limit? You mean like ensuring if wumbo _isn't_ activated, then we don't allow this value to be set? 

One other thing I think we should consider is adding a new default soft-limit if wumbo _is_ activated. Just to make sure users are protected somewhat, and need to _explicitly_ allow mega-wumbo channels.

2020-08-26 05:43 UTC, calvinrzachman commented
Hi @roasbeef, thanks for the review. I was hoping to get the test case and validation added in before you made a first pass, but alas. I’ve added those in and made a couple changes.

At first glance I didn’t like the idea of a default setting for `--maxchansize` overriding the wumbo config option which led me to where things are currently: 

- ANY explicit user setting of ` --maxchansize` is respected (both for wumbo and non-wumbo).
- For non-wumbo configurations this limit remains `16777215` satoshis by default as specified in BOLT-0002. NOTE: This is already enforced by [this](https://github.com/lightningnetwork/lnd/blob/ef69537c7f8d7b702f585831df8e3a746b8a756b/fundingmanager.go#L1257) existing code.
- For wumbo funding managers this limit is NOT enforced by default (currently indicated by zero value). We could modify this to impose a new new default soft-limit in the wumbo case as you mentioned.

Maybe there is a better way to do this than using a zero value. This breaks down should the user set `--maxchansize=0` but perhaps it's okay since that is most certainly not a valid setting anyway. An alternative way to distinguish between the zero value and an unset value is with pointers.

One more thing: Right now I only enforce `--maxchansize` inside `handleFundingOpen()` which I believe is in response to an OpenChannel message from a peer.  It makes sense to me to enforce this on channels created by user inside handleInitFundingMsg(). Let me know what you think and whether I took this in the wrong direction.

2020-08-26 05:47 UTC, calvinrzachman commented on config.go
> +		MaxChanSize:                   int64(MaxFundingAmount),
✅ added

2020-08-28 09:11 UTC, halseth reviewed
Thanks for the PR, awesome change 👍 

I agree that perhaps a soft-limit by default is preferred. If you opt into wumbo, then you should be able to open channels of any size you like, but IMO it should be a second opt-in to start accepting huuuge channels.

2020-09-01 00:13 UTC, calvinrzachman commented
At first a new larger default seemed to defeat the nature of WUMBO channels, but given that people will be entrusting their wealth to `lnd`, that's starting to sound like a better and better idea. 

Any thoughts on what the new default maximum channel size should be?

2020-09-11 00:22 UTC, Roasbeef commented
> Any thoughts on what the new default maximum channel size should be?



10 BTC?

2020-09-11 00:23 UTC, Roasbeef commented
>  If you opt into wumbo, then you should be able to open channels of any size you like, but IMO it should be a second opt-in to start accepting huuuge channels.

Yeh there's a distinction here:
  * pre wumbo .16 is the limit
  * post wumbo you can open any size you want 
  * post wumbo there's a new default soft limit for _accepting_
  * post wumbo, users can modify the default _acceptance_ max

2020-09-11 01:55 UTC, Roasbeef requested changes
This PR is super close! IMO we want to have a default soft-limit for for wumbo chans in place. In the past, we threw around a value of 10 BTC which seemed reasonable at the time. This would only be for _accepting_ the channels as mentioned. 

We'd like to tag our v0.11.1 version in a few days here, and I think this is really close, so I'd like to get it in.

2020-09-11 01:55 UTC, Roasbeef commented on config.go
> +		MaxChanSize:                   int64(0), // Do not enforce maxiumum channel size by default
I think we _do_ want to enforce it by default, but only when we're in wumbo mode. A default wumbo soft-cap of 10 BTC has been suggested.

2020-09-11 01:55 UTC, Roasbeef commented on config.go
> +		if !cfg.ProtocolOptions.Wumbo() && cfg.MaxChanSize > int64(MaxFundingAmount) {
👍

2020-09-11 01:55 UTC, Roasbeef commented on config.go
> +				"maximum channel size %v is greater than maximum non-wumbo channel size %v",
Should be cut to reside near the line limit.

2020-09-11 01:55 UTC, Roasbeef commented on fundingmanager.go
> +	// (marked by 0 value), then skip this check and permit channel creation of any size
Style nit: sentence should end in a period, and also be wrapped to 80 chars.

2020-09-12 16:20 UTC, calvinrzachman commented
Latest update contains enforcement for `10 BTC` default limit. I elected to setup defaults in `ValidateConfig()` inside `config.go` and keep the simplest check I could think of in the Funding Manager. Since the funding manager now trusts its config in determining the `MaxChanSize`, I added a new `itest` to verify that config.go handles explicit user setting of `--maxchansize` and both wumbo/non-wumbo defaults. 

I agree this is close. One thing I am unsure on right now is whether my setting of the default limits will screw up the case where lnd is run with Litecoin.  I will think on this a bit more and do my best to finish this PR off this weekend.

2020-09-15 02:06 UTC, Roasbeef commented
> One thing I am unsure on right now is whether my setting of the default limits will screw up the case where lnd is run with Litecoin.

The default can always be overridden in that case. FWIW, the 0.16 number itself was very Bitcoin specific.

2020-09-15 02:09 UTC, Roasbeef commented
The latest set of changes is looking pretty good to me! Final thing is to either squashed down these commits into one, or update the title+body for each of the commits. As the change is relatively contained, I think maybe we can just squash them into one. Thanks again for working on this!

2020-09-15 02:11 UTC, Roasbeef approved these changes
LGTM 🧬

Changed looking good to me, final nit is just to squash into a single commit. Will test this out a bit locally and also wait on the other reviewer before merging.

2020-09-15 02:20 UTC, calvinrzachman commented
@Roasbeef Squashed ✅ Thanks for the guidance on the way through. It was fun to start learning the 2nd most important codebase in the world. I'll be on the lookout for another issue/PR soon.

2020-09-15 16:22 UTC, cfromknecht approved these changes
Thanks @calvinrzachman!! Very clean PR, LGTM 👌

2020-09-15 17:22 UTC, halseth approved these changes

2020-09-15 22:31 UTC, merged