Fix top_centrality in sample-lnd.conf
lightningnetwork/lnd pull request #4668
Opened 2020-10-02 22:10 UTC by Empact

Correct me if I'm wrong, but this seems incorrect, and local testing confirms.

It's causing confusion, e.g. here: https://www.reddit.com/r/lightningnetwork/comments/j29ai3/how_to_enable_the_new_autopilot_heuristic_in_v0110/

2020-10-03 00:13 UTC, Roasbeef requested changes
Thanks for this fix! While you're at it, can you also make this the default ATPL heuristic? The relevant section of code to change is here: https://github.com/lightningnetwork/lnd/blob/master/config.go#L397

2020-10-03 03:14 UTC, Empact commented
@Roasbeef done 👍

2020-10-03 09:29 UTC, bhandras requested changes
The underlying problem is that the version of `go-flags` we use (1.4) does have an issue parsing map arguments it seems as it doesn't split them, nor is the documentation correct. @Empact could you please look into also updating go flags to the latest master?

2020-10-05 18:15 UTC, cfromknecht approved these changes
LGTM, thanks @Empact! 🏄‍♂️

2020-10-06 18:16 UTC, bhandras commented
> LGTM, thanks @Empact! surfing_man

I think it'd be important to update the `go-flags` with this PR as the map parsing in 1.4 is broken and therefore passing a linear combination of heuristics is not possible. WDYT @cfromknecht ?

2020-10-06 18:44 UTC, Empact commented
I'm happy to do that, just is taking a bit to find the time.

2020-10-06 18:58 UTC, Empact commented
After a cursory look, I haven't been able to identify the commit that was the fix. Does it not make sense to wait for a release? https://github.com/jessevdk/go-flags/issues/345

2020-10-07 20:32 UTC, cfromknecht commented
@Empact @bhandras you can supply a linear combination by passing multiple `--autopilot.heuristic` arguments, e.g.:
```
autopilot.heuristic=preferential:0.3
autopilot.heuristic=top_centrality:0.7
```

2020-10-07 20:33 UTC, cfromknecht commented
> Does it not make sense to wait for a release?

Good point, yes I think we should wait for a release 👍

2020-10-07 23:48 UTC, Roasbeef approved these changes
LGTM 🐚

2020-10-07 23:48 UTC, merged