lnrpc: allow AMP pay-addr override + bump invoice timeouts
lightningnetwork/lnd pull request #5336
Opened 2021-05-27 01:13 UTC by cfromknecht

This PR permits an AMP invoice to be "pseudo-reusable", where the invoice
paramters can be used multiple times so long as a new payment address is
supplied. This prevents additional round trips between payer and payee
to obtain a new invoice, even though the payments/invoices won't be
logically associated via the RPC interface like they would when the full
reusable invoices are deployed.

It also increases the default MPP expiry from 1 hour to 1 day. For the new AMP
invoices, we increase the interval to 1 month. The longer time frames
for AMP invoices is used so that the invoice can be pseudo reused as
implemented in the prior commit.

The BOLT 11 default of 1 hour is still preserved whenever the field is
missing in the payment request itself, but as of this commit the field
will always be set by lnd.

2021-05-27 02:15 UTC, Roasbeef requested changes
Straightforward change that should provide a lot of utility in the short term! Only blocking thing is that it looks like a case statement is flipped during invoice generation.

2021-05-27 02:15 UTC, Roasbeef commented on lnrpc/invoicesrpc/addinvoice.go
> +	case invoice.Amp:
I think this statement should be flipped? So `case !invoice.Amp`.

2021-05-27 02:15 UTC, Roasbeef commented on lntest/itest/lnd_amp_test.go
> +	// a new invoice will be JIT inserted under a different payment address
👍

2021-05-27 08:03 UTC, halseth requested changes
LGTM barring @Roasbeef's remark  ✅

2021-05-27 08:03 UTC, halseth commented on lnrpc/routerrpc/router_backend.go
> +		var payAddr = payReq.PaymentAddr
style nit: use `:=`

2021-05-27 08:03 UTC, halseth commented on lntest/itest/lnd_amp_test.go
> +	useExternalPayAddr bool) {
👍

2021-05-31 20:02 UTC, Roasbeef approved these changes
LGTM 🏓

2021-05-31 20:02 UTC, merged