docs: bump manual docker build to v0.12.1-beta
lightningnetwork/lnd pull request #5370
Opened 2021-06-09 23:51 UTC by RandyMcMillan

2021-06-10 19:20 UTC, wpaulino commented on docs/DOCKER.md
> +⛰  docker build --tag=myrepository/lnd --build-arg checkout=v0.12.1-beta .
Maybe it's worth waiting to update this once `v0.13.0-beta` is officially released?

2021-06-17 07:01 UTC, carlaKC reviewed
Can bump to 0.13.0 as suggested, then good to go.

2021-06-21 06:46 UTC, carlaKC requested changes

2021-06-21 06:46 UTC, carlaKC commented on docs/DOCKER.md
> +⛰  docker build --tag=myrepository/lnd --build-arg checkout=v0.13.1-beta .
s/v0.13.1-beta/v0.13.0-beta

2021-06-22 02:46 UTC, Roasbeef commented
Will hold off on merging this till the last item in the 0.13.1 milestone has been merged.

2021-12-07 12:45 UTC, lightninglabs-deploy commented
@randymcmillan, remember to re-request review from reviewers for your latest update

2021-12-10 13:26 UTC, lightninglabs-deploy commented
@randymcmillan, remember to re-request review from reviewers for your latest update

2021-12-10 13:49 UTC, carlaKC commented
Closing due to inactivity. Feel free to update and reopen!

2021-12-10 13:49 UTC, closed without merging