lnd: only set payment address if not empty in PaymentRequest
lightningnetwork/lnd pull request #5419
Opened 2021-06-22 09:44 UTC by bjarnemagnussen

## Background

This PR addresses an issue where not defining a payment address with the `SendPaymentRequest` results in a `payment_incorrect_details` error for:
* keysend payments, and 
* in LND versions <=0.11 when defining the payment directly using the pubkey in `Dest` and `PaymentHash` instead of using an invoice with `PaymentRequest`.

The error occurs as not defining a payment address with the `SendPaymentRequest` results in an _empty_ payment address byte array in the `paymentIntent` instead of a nil-value.

fixes #5413

2021-06-23 23:14 UTC, Roasbeef requested changes
Solid fix! IMO the only thing missing here is updating the itests (`testSingleHopInvoice`) to account for this change. Looking at the [existing test case for keysend we have](https://github.com/lightningnetwork/lnd/blob/master/lntest/itest/lnd_single_hop_invoice_test.go#L147) I don't see how this _wasn't_ already covered, given the request is identical to the proto sample you posted in the original issue.

2021-06-23 23:14 UTC, Roasbeef commented on rpcserver.go
> -	copy(payIntent.paymentAddr[:], rpcPayReq.PaymentAddr)
Ahh, so this ended up copying a _zero valued_ payment address, which was rejected as it's used as a shibboleth elsewhere in the codebase.

2021-06-23 23:15 UTC, Roasbeef commented
> I don't see how this wasn't already covered, given the request is identical to the proto sample you posted in the original issue.

Ah I think the difference here is all our itests [use `SendPaymentV2` and not the deprecated](https://github.com/lightningnetwork/lnd/blob/1287328678c2c6c31792287bb413d46714af0c9c/lntest/itest/lnd_test.go#L13656) variant on the main Lightning service.

2021-06-24 06:02 UTC, bjarnemagnussen commented
Right, I was also wondering why the itest hadn't picked this up but just as you mention it is not tested for this `SendPayment` (probably due to deprecation?).

2021-06-24 22:45 UTC, Roasbeef commented
NP, it all makes sense now, and also explains why we didn't catch this when testing on the CLI as the CLI uses all the v2 calls. Given that we worked to move all the integration tests over to using the v2 APIs, I think this can land as is.

2021-06-24 22:46 UTC, Roasbeef approved these changes
LGTM 🛰

Ran the itests locally, it's hitting some failures due to a regression (after 0.13) that #5429 should fix.

2021-06-24 22:46 UTC, merged