chainntnfs: populate spendsByHeight during historical dispatch
lightningnetwork/lnd pull request #5465
Opened 2021-07-02 16:46 UTC by Crypt-iQ

If lnd restarts, a historical dispatch is performed, and then a
re-org of the spend occurs at tip, the caller would never be
notified of the re-org.

2021-07-29 22:43 UTC, wpaulino requested changes
Nice find! Looks like we should add a unit test as it's uncovered.

2021-08-06 22:18 UTC, Roasbeef requested changes
I think this is only missing a unit test to reproduce an erroneous scenario as Wilmer mentioned.

2021-09-01 20:50 UTC, Crypt-iQ commented
I've added a unit test, and a reorg notification is now properly dispatched.  The unit test fails without the patch.

2021-09-13 18:58 UTC, Roasbeef approved these changes
LGTM 👒

2021-09-13 18:58 UTC, merged