docs: Remove pruned node warning.
lightningnetwork/lnd pull request #5765
Opened 2021-09-19 18:26 UTC by sime

In #5553 `docs/INSTALL.md` was updated to reflect that prune nodes are supported.

#### Pull Request Checklist

- [ ] All changes are Go version 1.15 compliant
- [ ] Your PR passes all CI checks. If a check cannot be passed for a justifiable reason, that reason must be stated in the commit message and PR description.
- [x] If this is your first time contributing, we recommend you read the [Code Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md)
   - [ ] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
   - [ ] Commits have a logical structure according to [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)
- [ ] For new code: Code is accompanied by tests which exercise both the positive and negative (error paths) conditions (if applicable)
- [ ] For bug fixes: If possible, code is accompanied by new tests which trigger the bug being fixed to prevent regressions
- [ ] Any new logging statements use an appropriate subsystem and logging level
- [x] For code and documentation: lines are wrapped at 80 characters (the tab character should be counted as 8 characters, not 4, as some IDEs do per default)
- [ ] A description of your changes [should be added to running the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes) for the milestone your change will land in.

2021-09-20 06:29 UTC, guggero reviewed
Thanks for the update. See inline comments.

2021-09-20 06:29 UTC, guggero commented on docs/safety.md
> +  - [The `-txindex` flag](the--txindex-flag)
The links need a hash/pound (`#`) sign, otherwise they won't work.

2021-09-20 06:30 UTC, guggero commented on docs/safety.md
>  In addition to not running a pruned node, it is recommended to run `bitcoind`
Perhaps we should re-word this now? That for performance reasons it is recommended to _not_ run a pruned node if possible and to enable the `-txindex` flag as well?

2021-09-20 14:52 UTC, sime commented
@guggero Whoops. My bad, it's sorted now.

2021-09-22 04:17 UTC, yyforyongyu requested changes
Thanks for the PR. I think you need to squash your commits into one, and use the `skip ci` tag suggested in our [developer guide](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#ideal-git-commit-structure).

2021-09-22 07:23 UTC, sime commented
@yyforyongyu Squash and appended `[skip ci]`

2021-09-22 07:38 UTC, guggero approved these changes

2021-09-23 03:18 UTC, yyforyongyu approved these changes

2021-09-23 07:17 UTC, merged