Export backend credentials
lightningnetwork/lnd pull request #6088
Opened 2021-12-14 00:19 UTC by arshbot

Reverts and replaces https://github.com/lightningnetwork/lnd/pull/6050, as the values were not accessible if the type was the `BackendConfig` interface

#### Pull Request Checklist

- [ ] All changes are Go version 1.16 compliant
- [ ] Your PR passes all CI checks. If a check cannot be passed for a justifiable reason, that reason must be stated in the commit message and PR description.
- [ ] If this is your first time contributing, we recommend you read the [Code Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md)
   - [ ] The code being submitted is commented according to [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation)
   - [ ] Commits have a logical structure according to [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure)
- [ ] For new code: Code is accompanied by tests which exercise both the positive and negative (error paths) conditions (if applicable)
- [ ] For bug fixes: If possible, code is accompanied by new tests which trigger the bug being fixed to prevent regressions
- [ ] Any new logging statements use an appropriate subsystem and logging level
- [ ] For code and documentation: lines are wrapped at 80 characters (the tab character should be counted as 8 characters, not 4, as some IDEs do per default)
- [ ] A description of your changes [should be added to running the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes) for the milestone your change will land in, or,
- [ ] If a PR only fixes a trivial issue, such as updating documentation on a small scale, fix typos, or any changes that do not modify the code, the commit message should end with [skip ci] to skip the CI checks.

2021-12-15 13:50 UTC, guggero requested changes
CI steps fail, other than that looks good.

2021-12-15 13:50 UTC, guggero commented on lntest/bitcoind_common.go
> +func (b BitcoindBackendConfig) Credentials() (string, string, string, error) {
You need the same method in the `BtcdBackendConfig` as well. That's why the linter and all tests currently fail.

2021-12-15 13:50 UTC, guggero commented on docs/release-notes/release-notes-0.14.2.md
> +* Harsha Goli
Could just squash this commit with the last one so it doesn't look like you're removing then adding people again to the contributor list.

2021-12-16 17:49 UTC, guggero approved these changes

2022-01-05 11:06 UTC, bhandras approved these changes
Release notes needs to be updated, other than that LGTM :+1:

2022-01-11 10:02 UTC, merged