Typo fixes and code cleanup
lightningnetwork/lnd pull request #6423
Opened 2022-04-16 22:57 UTC by tvolk131

## Change Description
Various documentation typo fixes, a simple code modification, and removal of two empty files

## Steps to Test
None

2022-04-18 03:29 UTC, yyforyongyu requested changes
Thank you for the PR! Please refer to [our contribution guide](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#ideal-git-commit-structure) regarding how to structure your commits and commit messages. And I'd suggest separating the changes into two commits if you are touching both the docs and the code.

2022-04-26 09:51 UTC, lightninglabs-deploy commented
@tvolk131, remember to re-request review from reviewers when ready

2022-05-03 10:40 UTC, lightninglabs-deploy commented
@tvolk131, remember to re-request review from reviewers when ready

2022-05-03 20:58 UTC, tvolk131 commented on channeldb/payment_control.go
> -		payment = nil
Ahh gotcha. Done.

2022-05-04 12:50 UTC, guggero approved these changes
LGTM, thanks!

2022-05-05 05:33 UTC, yyforyongyu approved these changes
LGTM🥳

2022-05-05 07:42 UTC, merged