rpc: verify address is for correct net
lightningnetwork/lnd pull request #6448
Opened 2022-04-23 02:11 UTC by torkelrogstad

## Change Description

Verify that the addresses we're decoding when sending coins onchain are
for the correct network. Without this check we'll convert the users
addresses to their equivalent on other networks, which is a gross
violation of the principle of least astonishment.

## Steps to Test

Prior to this commit:

1. Run a node on regtest
2. Issue either a `sendmany` or `sendcoins` RPC, with a _mainnet or testnet_ address
3. Observe that the address is accepted, and converted into a regtest address.

After this commit, step 2 fails. 

## Pull Request Checklist
### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.
  There doesn't seem to be any tests for this, at least not based on a quick code search. Would be happy to implement if I'm wrong. 

### Code Style and Documentation
- [x] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [x] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [x] ~Any new logging statements use an appropriate subsystem and logging level.~
- [x]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

2022-04-23 11:42 UTC, guggero approved these changes
Thanks for the fix! LGTM :tada:

2022-04-23 11:53 UTC, guggero requested changes
Actually, while we're at it, we should probably also add the check here:
- https://github.com/lightningnetwork/lnd/blob/master/lnrpc/walletrpc/walletkit_server.go#L1030
- https://github.com/lightningnetwork/lnd/blob/master/lnrpc/invoicesrpc/addinvoice.go#L277
- https://github.com/lightningnetwork/lnd/blob/master/rpcserver.go#L2474

Or, to fix the underlying assumption that (because it takes the net params as the second parameter) `DecodeAddress` actually checks that the address belongs to the correct network, we should perhaps add the check there?
Looking at the code, this seems to only be possible with non-Segwit (non-bech32) addresses in the first place.

2022-04-23 12:24 UTC, torkelrogstad commented
> Or, to fix the underlying assumption that (because it takes the net params as the second parameter) DecodeAddress actually checks that the address belongs to the correct network, we should perhaps add the check there?

Do you mean changing `btcutil`? That sounds like a pretty big behavioral change in how `DecodeAddress` works

2022-04-23 13:14 UTC, guggero commented
> Do you mean changing btcutil? That sounds like a pretty big behavioral change in how DecodeAddress works

Yes, maybe it's too big of a change. But maybe it would be worth adding a comment in the `btcutil` library that for legacy addresses the network isn't checked.

2022-04-23 13:54 UTC, torkelrogstad commented
Found another place, in `chancloser`

https://github.com/lightningnetwork/lnd/blob/f13399bc494d9ad78c4ecbc081e027ee3b41485f/lnwallet/chancloser/chancloser.go#L710-L728

For the sake of returning errors that look the same in all places, and ergonomics, would it be an idea to introduce a new wallet in `btcutil`? Filed an issue in `btcd`, figured that was a better place to discuss: https://github.com/btcsuite/btcd/issues/1846

2022-04-25 09:22 UTC, guggero commented
> Looking at the code, this seems to only be possible with non-Segwit (non-bech32) addresses in the first place.

Oops, I was wrong there. I read the `if chaincfg.IsBech32SegwitPrefix(prefix) {` incorrectly. It doesn't check that the prefix is for the given network, it just checks if it's _any_ valid prefix...

I like your idea of adding `DecodeAddressForNet` in `btcd`. Since we'll be bumping the dependency to that project anyway, I'd rather use that method everywhere in `lnd` (after the PR there was merged) than add the `IsForNet` check everywhere.

2022-05-02 09:56 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-05-09 10:40 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-05-23 15:07 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-05-30 15:31 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-06-06 16:02 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-06-20 16:39 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-06-27 16:41 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-07-04 16:58 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-07-18 18:09 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-07-25 18:40 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-08-01 19:14 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-08-08 20:00 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-08-15 20:48 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-08-22 21:34 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-09-05 23:07 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-09-12 23:08 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-09-19 23:25 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-09-26 23:41 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-10-03 23:55 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-10-11 00:47 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-10-18 01:46 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-10-25 02:00 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-11-01 02:48 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-11-15 03:49 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-11-22 03:50 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-11-29 04:43 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-12-06 04:52 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-12-13 04:57 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-12-20 05:29 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2022-12-27 05:47 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-01-03 06:07 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-01-10 06:35 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-01-17 07:22 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-01-24 08:04 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-01-31 08:33 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-02-07 09:17 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-02-14 09:21 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-02-21 09:58 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-02-28 10:07 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-03-07 10:10 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-03-14 11:12 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-04-04 03:09 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-04-11 03:33 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-04-18 03:42 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-04-25 04:23 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-05-02 04:42 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-05-09 05:37 UTC, lightninglabs-deploy commented
@torkelrogstad, remember to re-request review from reviewers when ready

2023-05-12 10:37 UTC, guggero commented
Replaced by/included in https://github.com/lightningnetwork/lnd/pull/7689, original commit author credits are preserved.

2023-05-12 10:37 UTC, closed without merging