lnwallet: check htlc log against nil in localLogUpdateToPayDesc
lightningnetwork/lnd pull request #6624
Opened 2022-06-07 13:43 UTC by yyforyongyu

This PR mitigates issue #6617 by providing a nil-check to avoid the segfault seen. More investigation is needed to properly fix the issue.

2022-08-31 23:01 UTC, Roasbeef requested changes

2022-08-31 23:01 UTC, Roasbeef commented on docs/release-notes/release-notes-0.15.1.md
> +* [A nil-check](https://github.com/lightningnetwork/lnd/pull/6624) is added
Should be in the 0.16 release notes now

2022-08-31 23:01 UTC, Roasbeef commented on lnwallet/channel.go
> +	// Patch the commen fields.
commen -> common

2022-09-01 02:43 UTC, yyforyongyu commented on docs/release-notes/release-notes-0.15.1.md
> +* [A nil-check](https://github.com/lightningnetwork/lnd/pull/6624) is added
fixed.

2022-09-01 02:43 UTC, yyforyongyu commented on lnwallet/channel.go
> +	// Patch the commen fields.
fixed.

2022-09-08 02:58 UTC, lightninglabs-deploy commented
@yyforyongyu, remember to re-request review from reviewers when ready

2022-09-15 03:04 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-09-22 03:24 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-09-29 03:40 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-10-06 03:50 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-10-13 04:42 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-10-20 05:43 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-10-27 06:27 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-11-03 06:48 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-11-10 07:20 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-11-17 07:52 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-11-24 07:58 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-12-01 08:01 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-12-08 08:12 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-12-15 08:59 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-12-22 09:27 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2022-12-29 09:46 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-01-05 10:09 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-01-12 10:29 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-01-26 11:23 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-02-02 11:53 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-02-09 12:51 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-02-16 13:51 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-03-02 15:47 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-03-09 15:49 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-03-16 16:47 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-04-04 03:09 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-04-11 03:33 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-04-18 03:42 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-04-25 04:23 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-05-02 04:42 UTC, lightninglabs-deploy commented
@roasbeef: review reminder

2023-05-04 00:25 UTC, yyforyongyu commented
!lightninglabs-deploy mute 30

2024-05-02 06:59 UTC, closed without merging