chainreg: shutdown if backend node doesn't support taproot
lightningnetwork/lnd pull request #6798
Opened 2022-08-05 02:59 UTC by Roasbeef

In this commit, we add a check during normal node construction to see if
the backend node supports Taproot. If it doesn't, then we want to
shutdown and force the user to take note.

To check if the node supports Taproot, we'll first try the normal
getblockchaininfo call. If this works, cool, then we can rely on the
value. If it doesn't, then we'll fall back to the getdeploymentinfo call
which was added in a recent version of bitcoind [1]. Newer versions of
bitcoind might also have this call, and the getblockchaininfo call, but
not actually populate the softforks field [2]. In this case, we'll fall
back, and we also account for the case when the getblockchaininfo RPC is
removed all together.

[1]: https://github.com/bitcoin/bitcoin/pull/23508
[2]: https://github.com/bitcoin/bitcoin/pull/25114

2022-08-05 07:53 UTC, bhandras approved these changes
LGTM :rocket:

2022-08-05 09:04 UTC, yyforyongyu requested changes
hmmm looks like the itest cannot be started.

2022-08-05 23:03 UTC, Roasbeef commented on chainreg/taproot_check.go
> +	_, ok := info.Deployments["taproot"]
So we don't actually start up until the chain backend is "current", so the assumption is that as long as they know about it, it'll be active once they reach current day. Will do some more testing in the background. The goal with this PR is to be able to handle basically all the current state, and also the future state where certain calls are deprecated, then removed all together.

2022-08-06 00:20 UTC, Roasbeef commented on chainreg/chainregistry.go
> +		// Before we continue any further, we'll ensure that the
Opted to create a temporary REST client for btcd, which seems to be working locally. 

I was originally going to make this a healthcheck, but it's more of a one time thing, so figured we can just stick it in during initiliaztion. 

Another option is to put the check a bit further down the pipeline, so once the daemon is actually able to start in `lnd.go`, but at that point we don't have the `*rpcclient.Client`, so I'd need to make an assumption to type cast to get the information.

2022-08-06 00:21 UTC, Roasbeef commented on chainreg/taproot_check.go
> +		if _, ok := chainInfo.SoftForks.Bip9SoftForks["taproot"]; ok {
Ah yeah, for `bitcoind` newer versions don't specify the field (unless you run w/ a special arg). Modified to check the pointer before accessing.

2022-08-08 01:42 UTC, yyforyongyu approved these changes
Cool LGTM👍

2022-08-08 22:27 UTC, merged