fixing inconsistent flag naming in lncli queryRoutes
lightningnetwork/lnd pull request #6958
Opened 2022-09-30 20:49 UTC by aljazceru

outgoing chan id flag has two different namings:
- **outgoing_chanid** in queryroutes 
- **outgoing_chan_id** in payinvoice 

This PR unifies that to **outgoing_chan_id** for the sake of consistency

2022-10-07 13:12 UTC, ellemouton approved these changes
LGTM 🔥 agreed that the consistency is nice. 

Question to next reviewer: how do we feel about breaking the "API" of lncli like this? ie, it will impact users who have written scripts that interact with LND via lncli. But I guess they should probably use the grpc API directly for that anyways.

2022-10-15 04:42 UTC, yyforyongyu requested changes
Thanks for the change! The commit message is a bit off, and missing a release note for this change, which is important here as it breaks the old cli command. For details, please read [contribution guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#ideal-git-commit-structure).

2022-10-24 01:03 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2022-10-31 01:51 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2022-11-07 05:21 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2022-11-14 05:56 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2022-11-21 06:47 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2022-11-28 07:46 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2022-12-05 07:59 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2022-12-12 08:06 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2022-12-19 08:42 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2022-12-26 09:01 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-01-02 09:21 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-01-09 09:47 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-01-16 10:31 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-01-23 11:06 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-01-30 11:35 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-02-06 12:17 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-02-13 12:19 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-02-20 13:01 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-02-27 14:02 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-03-13 15:12 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-04-04 03:08 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-04-11 03:32 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-04-18 03:42 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-04-25 04:23 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-05-02 04:42 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-05-09 05:37 UTC, lightninglabs-deploy commented
@aljazceru, remember to re-request review from reviewers when ready

2023-05-12 10:37 UTC, guggero commented
Replaced by/included in https://github.com/lightningnetwork/lnd/pull/7689, original commit author credits are preserved.

2023-05-12 10:37 UTC, closed without merging