addinvoice simplify usage of PopulateHopHints
lightningnetwork/lnd pull request #7065
Opened 2022-10-20 10:45 UTC by sputn1ck

This PR simplifies the usage of `PopulateHopHints by` removing the use of the channeldb.OpenChannel struct to the previously used HopHintInfo

2022-10-20 10:46 UTC, sputn1ck commented on lnrpc/invoicesrpc/addinvoice.go
>  	// FetchAllChannels retrieves all open channels currently stored
godoc would need to be updated

2022-10-20 10:46 UTC, sputn1ck commented on lnrpc/invoicesrpc/addinvoice.go
> +// channeldb.OpenChannel
missing dot

2022-10-20 11:03 UTC, positiveblue requested changes
The changes LGTM + will make it easier for other applications to use this method with `lndclient`

2022-10-20 11:03 UTC, positiveblue commented on lnrpc/invoicesrpc/addinvoice.go
> +		if !oc.IsPublic {
nit: now that we already have the `HopHintInfo` here maybe we can do `if !oc.IsPublic && oc.IsActive {`

2022-10-20 11:03 UTC, positiveblue commented on lnrpc/invoicesrpc/addinvoice.go
>  func shouldIncludeChannel(cfg *SelectHopHintsCfg,
nit: rename to `shouldIncludeHopHint`?

2022-10-20 11:03 UTC, positiveblue commented on lnrpc/invoicesrpc/addinvoice.go
> +	channel *HopHintInfo,
nit: `hopHintInfo`?

2022-10-27 11:40 UTC, lightninglabs-deploy commented
@sputn1ck, remember to re-request review from reviewers when ready

2022-11-03 12:01 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@sputn1ck, remember to re-request review from reviewers when ready

2022-11-10 12:32 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@sputn1ck, remember to re-request review from reviewers when ready

2022-11-24 13:12 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@sputn1ck, remember to re-request review from reviewers when ready

2022-12-01 13:16 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@sputn1ck, remember to re-request review from reviewers when ready

2022-12-08 13:25 UTC, lightninglabs-deploy commented
@positiveblue: review reminder

2022-12-15 14:11 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2022-12-22 14:40 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2022-12-29 14:59 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-01-05 15:22 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-01-12 15:45 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-01-19 15:57 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-01-26 16:38 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-02-02 17:07 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-02-16 19:06 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-02-23 19:43 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-03-02 20:01 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-03-09 20:03 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-03-16 20:59 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-04-04 03:08 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-04-11 03:32 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-04-18 03:42 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-04-25 04:23 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-05-02 04:42 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-05-09 05:36 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-05-16 06:08 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-05-23 06:11 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-05-30 06:37 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-06-13 07:35 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-06-27 08:23 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-07-04 09:04 UTC, lightninglabs-deploy commented
@bhandras: review reminder
@positiveblue: review reminder

2023-07-28 13:45 UTC, lightninglabs-deploy commented
Closing due to inactivity

2023-07-28 14:49 UTC, lightninglabs-deploy commented
Closing due to inactivity

2023-07-28 15:52 UTC, lightninglabs-deploy commented
Closing due to inactivity

2023-07-28 16:03 UTC, closed without merging