revise help text for addinvoice lncli command
lightningnetwork/lnd pull request #7135
Opened 2022-11-10 03:46 UTC by st4rgut24

## Change Description
Revise help text for addinvoice lncli command

## Pull Request Checklist

### Code Style and Documentation
- [x] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

2022-11-10 05:43 UTC, yyforyongyu requested changes
Thanks for the PR! According to our contribution guidelines,
> [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or [skip ci] in the commit message for small changes.

could you change your commit message to `cli: revise help text for addinvoice lncli command [skip ci]`

2022-11-10 08:46 UTC, guggero requested changes

2022-11-10 08:46 UTC, guggero commented on cmd/lncli/cmd_invoice.go
> +	to specify the amount of satoshis they wish to receive.`,
I think this is the wrong way around. If the payee wants to specify the number of satoshis to receive, they use the `--amt` field. If they want to give the option to the other side (the **payer**), then they leave the amount as zero. So this should say "allows the payer ... they with to send".

2022-11-11 06:58 UTC, yyforyongyu commented
Thanks for the update. I think you need to squash the two commits and then we'd be good to go.

2022-11-18 07:14 UTC, lightninglabs-deploy commented
@st4rgut24, remember to re-request review from reviewers when ready

2022-11-18 16:08 UTC, st4rgut24 commented
@yyforyongyu , @guggero  ready for a final review

2022-11-18 17:28 UTC, guggero approved these changes

2022-11-18 17:42 UTC, yyforyongyu approved these changes

2022-11-18 17:43 UTC, merged