Fix typos in selfsigned.go
lightningnetwork/lnd pull request #7321
Opened 2023-01-14 22:57 UTC by bshramin

## Change Description
This pull request fixes two typos in the `selfsigned.go` file.

## Steps to Test
I don't think any testing is required since this pull request only changes typos in comments.

## Pull Request Checklist
### Testing
- [X] Your PR passes all CI checks.
- [X] Tests covering the positive and negative (error paths) are included.
- [X] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [X] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [X] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [X] Any new logging statements use an appropriate subsystem and logging level.
- [X]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

2023-01-15 19:49 UTC, yyforyongyu requested changes
Thanks for the PR. Based on
> [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or [skip ci] in the commit message for small changes.

This is missing a `[skip ci]`.

2023-01-15 22:15 UTC, bshramin commented
> Thanks for the PR. Based on
> 
> > [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or [skip ci] in the commit message for small changes.
> 
> This is missing a `[skip ci]`.

I added it to the commit message.

2023-01-15 22:37 UTC, yyforyongyu approved these changes
LGTM, thanks!

2023-01-16 07:37 UTC, ellemouton approved these changes

2023-01-16 08:54 UTC, merged