build: fix Makefile ldflags for mac and mobile
lightningnetwork/lnd pull request #7359
Opened 2023-01-25 17:33 UTC by djkazic

## Change Description
PR [6963](https://github.com/lightningnetwork/lnd/pull/6963) refactored the Makefile to have a more streamlined approach to ldflags. However, in the process it also introduced two subtle but critical errors.
1. The `-ldflags` parameter is missing.
2. The ldflags themselves are not wrapped in a string.

The result is that the arguments are mangled, and gomobile complains about `-s` not being a parameter.

Before 6963:
```GO111MODULE=off /home/synthlock/go/bin/gomobile bind -target=android -tags="mobile dev autopilotrpc chainrpc invoicesrpc neutrinorpc peersrpc routerrpc signrpc verrpc walletrpc watchtowerrpc wtclientrpc" -ldflags " -s -w -X github.com/lightningnetwork/lnd/build.Commit=v0.15.5-beta -X github.com/lightningnetwork/lnd/build.CommitHash=c0a09209782b1c62c3393fcea0844e095c25046b -X github.com/lightningnetwork/lnd/build.GoVersion=go1.18.10 -X github.com/lightningnetwork/lnd/build.RawTags=" -v -o /home/synthlock/go/src/github.com/lightningnetwork/lnd/mobile/build/android/Lndmobile.aar github.com/lightningnetwork/lnd/mobile```
After 6963:
```GO111MODULE=off /home/synthlock/go/bin/gomobile bind -target=android -tags="mobile dev autopilotrpc chainrpc invoicesrpc neutrinorpc peersrpc routerrpc signrpc verrpc walletrpc watchtowerrpc wtclientrpc"  -s -w -buildid= -X github.com/lightningnetwork/lnd/build.Commit=kvdb/v1.4.1-6-g9187d4679 -v -o /home/synthlock/go/src/github.com/lightningnetwork/lnd/mobile/build/android/Lndmobile.aar github.com/lightningnetwork/lnd/mobile```

This PR adds in the correct behavior for ldflag passing. `-ldflags` is explicitly set in each affected stanza, and the ldflags are wrapped in a string.

## Steps to Test
`make android` on v0.15.5 release versus master.

## Pull Request Checklist
### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [x] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [x] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [x] Any new logging statements use an appropriate subsystem and logging level.
- [x]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

2023-01-26 11:18 UTC, guggero requested changes
Thanks for the fix! I can confirm this fixes at least one part of the issues.
It seems like we need some additional things to fix the mobile build. Not sure what exactly changed, but the same changes were necessary to get LNC compiling (see https://github.com/lightninglabs/lightning-node-connect/pull/66).

Here's the diff that enabled me to get Android compilation working. Would be great if you could test iOS as I don't have the Xcode framework installed.

[mobile.diff.txt](https://github.com/lightningnetwork/lnd/files/10508685/mobile.diff.txt)

2023-01-27 20:37 UTC, djkazic commented
@guggero Interesting. Does this not build for you? I can apply the patch, but it seems like the main changes there are bumping the gomobile and bind deps.

2023-01-31 15:38 UTC, djkazic commented
Commit messages edited and signed.

2023-02-07 16:39 UTC, lightninglabs-deploy commented
@djkazic, remember to re-request review from reviewers when ready

2023-02-13 10:49 UTC, guggero approved these changes
Nice, this now builds for Android on my machine.
@hsjoberg sine you probably have a dev environment for all the builds you target in Blixt, could you please take a look and make sure this works with the latest iOS versions you target?

2023-02-13 10:49 UTC, guggero commented on docs/release-notes/release-notes-0.16.0.md
> +* [ldflags were being incorrectly passed](
nit: "... in mobile builds"?

2023-02-13 10:49 UTC, guggero commented on Makefile
> +GOMOBILE_BIN := $(GO_BIN)/gomobile
nit: commit message should reflect what the commit does, not the action the developer took. I know I supplied the patch, so I would've used something like "multi: bump to latest gomobile version, fix mobile build".

2023-02-13 19:48 UTC, hsjoberg commented
@guggero I can confirm iOS and macOS targets build and work with this PR.

2023-03-29 14:49 UTC, djkazic commented
@guggero should I rebase this one too?

2023-03-31 13:57 UTC, djkazic commented
@guggero rebased PR and branch on 0.16.1 staging branch

2023-04-04 02:08 UTC, Roasbeef commented
Approved CI run.

2023-04-05 01:05 UTC, merged