HTLC Interceptor: Fix nil pointer dereference
lightningnetwork/lnd pull request #7392
Opened 2023-02-10 01:01 UTC by adiabat

## Change Description
This fixes an issue where LND can crash due to an invalid RPC message from an HTLC interceptor.  Not a security or DoS concern as this is from authenticated messages coming in on grpc, but it's a pretty easy mistake to make on the interceptor side (just leave off the `IncomingCircuit`) so I think it's worth fixing.

All this PR does is add a `==nil` check and returns an error if `IncomingCircuit` is nil.  

Other places you could put this check would be in `(r *forwardInterceptor) run()` above (or maybe in the `Recv()` function somehow?) but this seemed like the most straightforward place.

## Steps to Test
To test: 
Run LND.  
Connect an HTLC interceptor, but in the interceptor code, don't specify an `IncomingCircuitKey` in the `routerrpc.ForwardHtlcInterceptResponse`.  
The first time LND tries to forward an HTLC, it will get a `ForwardHtlcInterceptResponse` without an `IncomingCircuitKey` and crash with `panic: runtime error: invalid memory address or nil pointer dereference`

Apply this patch, try the same thing, and LND will disconnect the interceptor with this showing up in the logs:

`[ERR] RPCS: [/routerrpc.Router/HtlcInterceptor]: rpc error: code = InvalidArgument desc = CircuitKey missing
 from ForwardHtlcInterceptResponse`

(I dunno if "InvalidArgument" is the right error code but seems close enough)

## Pull Request Checklist
### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

2023-02-10 08:31 UTC, ellemouton requested changes
Hi @adiabat! Good catch! Thanks for the PR!

I left a small simplification suggestion. Also, please see [our contribution guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#model-git-commit-messages) for how to structure your commit title and message. Thanks!

You also need to please include an entry in the release notes :)

2023-02-10 08:31 UTC, ellemouton commented on lnrpc/routerrpc/forward_interceptor.go
> +	if in == nil || in.IncomingCircuitKey == nil {
I don't think `in` is ever expected to be `nil`. So can just do the second check

2023-02-10 18:41 UTC, adiabat commented
Thanks @ellemouton - I removed the `in == nil` check, added an entry to the release notes, and shortened the top line of the commit message.

2023-02-11 06:11 UTC, ellemouton approved these changes
LGTM 🔥 Thanks for the fix!

2023-02-13 08:55 UTC, guggero approved these changes
Thanks for the fix, LGTM :tada:

2023-02-13 10:43 UTC, merged