updated comments
lightningnetwork/lnd pull request #7581
Opened 2023-04-05 14:10 UTC by Satarupa22-SD

## Change Description
Description of change / link to associated issue.
Updated the comments related to GetInfo Function.
Issue Title : Wrong Comment in GetInfo function #7482
link : https://github.com/lightningnetwork/lnd/issues/7482

## Steps to Test
Steps for reviewers to follow to test the change.

## Pull Request Checklist
### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

2023-04-05 18:22 UTC, yyforyongyu requested changes
Thanks for the PR! Please read [the contribution guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) for formats and git messages. A quick way to test is to run `make lint` for the PR.

2023-04-12 18:26 UTC, lightninglabs-deploy commented
@satarupa22-sd, remember to re-request review from reviewers when ready

2023-04-19 18:32 UTC, lightninglabs-deploy commented
@satarupa22-sd, remember to re-request review from reviewers when ready

2023-04-26 19:03 UTC, lightninglabs-deploy commented
@satarupa22-sd, remember to re-request review from reviewers when ready

2023-05-03 19:30 UTC, lightninglabs-deploy commented
@satarupa22-sd, remember to re-request review from reviewers when ready

2023-05-04 00:07 UTC, yyforyongyu commented
!lightninglabs-deploy mute 30d

2023-05-12 10:37 UTC, guggero commented
Replaced by/included in https://github.com/lightningnetwork/lnd/pull/7689, original commit author credits are preserved.

2023-05-12 10:37 UTC, closed without merging