routing: fix `index out of range` panic
lightningnetwork/lnd pull request #7799
Opened 2023-06-30 12:36 UTC by positiveblue

Make sure that we do not crash the node trying to access an invalid position for an array (-1) in `BuildRoute`.

2023-06-30 12:45 UTC, guggero reviewed
Thanks for the fix!

2023-06-30 12:45 UTC, guggero commented on routing/router.go
> +		var fromNode route.Vertex
Should we move this into the `if edge == nil {` branch to make it more explicit we're only using this in the error/not found case?
Also:
```
fromNode := source
if i > 0 {
    fromNode := hopts[i-1]
}
```
?

2023-06-30 14:02 UTC, guggero approved these changes
LGTM :taco:

2023-06-30 14:08 UTC, Crypt-iQ approved these changes
lgtm pending ci 🦖

2023-06-30 14:27 UTC, Roasbeef requested changes

2023-06-30 14:27 UTC, Roasbeef commented on routing/router.go
> +			fromNode := source
Can we also add an itest to hit this case? 

Also is this the expected behavior? That the source becomes the default from node if only a single edge was specified?

2023-07-07 14:36 UTC, lightninglabs-deploy commented
@positiveblue, remember to re-request review from reviewers when ready

2023-07-14 15:21 UTC, lightninglabs-deploy commented
@positiveblue, remember to re-request review from reviewers when ready

2023-07-21 15:30 UTC, lightninglabs-deploy commented
@positiveblue, remember to re-request review from reviewers when ready

2023-07-27 18:17 UTC, Roasbeef approved these changes
LGTM 🍾

2023-07-27 18:17 UTC, merged