fix: lncli description connect/disconnect peer
lightningnetwork/lnd pull request #8053
Opened 2023-10-03 10:16 UTC by kilrau

## Change Description
Fix description of `lncli connect` & `lncli disconnect`

## Steps to Test
`lncli connect --help` & `lncli disconnect --help`

## Pull Request Checklist
### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

2023-10-03 10:32 UTC, guggero approved these changes
Thanks, LGTM :tada:

2023-10-03 14:27 UTC, dstadulis approved these changes
Thanks improving the accuracy!

2023-10-04 16:04 UTC, saubyk approved these changes
Ack

2023-10-04 16:08 UTC, guggero requested changes

2023-10-04 16:08 UTC, guggero commented on cmd/lncli/commands.go
> +	Usage:     "Disconnect a remote lightning peer identified by public key.",
The linter is failing on a too long line now, need to break this string.

2023-10-05 08:12 UTC, guggero commented
Thanks. Can you please squash the commits into a single one, using the [prefix as described in the contribution guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#ideal-git-commit-structure), then I can merge.

2023-10-05 20:27 UTC, merged