lnrpc: add NoHash option to signer.SignMessage rpc
lightningnetwork/lnd pull request #8098
Opened 2023-10-17 06:06 UTC by orbitalturtle

This PR adds the option to _not_ hash the message before signing it with `signer.SignMessage`. I'm running into a scenario where the message I need to pass into this API call is already hashed. 
 
I'm need this when needing a Schnorr signature of the message, so I made the change for that particular circumstance. But if this would be useful in a non-Schnorr scenario as well, I'd be happy to expand the change.

2023-10-17 06:30 UTC, guggero requested changes
Thanks for the PR. Though I'm not sure this is safe. Can you add more context to why the message can't be given to the RPC in a non-hashed form?

2023-10-17 06:30 UTC, guggero commented on lnrpc/signrpc/signer.proto
> +    bool compact_sig = 5;
We can't just re-number proto message fields, that would break backward compatibility.

2023-10-17 06:30 UTC, guggero commented on keychain/btcwallet.go
> +                digest = msg
This is really quite dangerous, especially if the message here is arbitrary input provided by the user. If the message happens to be a transaction hash or a p2p message, one could extract funds from the node or create fake gossip traffic. I'm honestly not sure if we should even allow this at all.

2023-10-17 06:57 UTC, orbitalturtle commented
@guggero Gotcha, that makes sense, thanks for taking a look. So I'm working on this for LNDK. We're currently working on supporting paying bolt 12 offers, and part of the process is to sign the invoice request... the data LDK needs to pass to LND is already hashed. I had first looked into changing this on LDK's side -- to try to pass in an unhashed value into the SignMessage api. But the hashing formula for is a bit more complicated just a SHA256 (it requires a merkle root as well alongside it) https://github.com/lightningdevkit/rust-lightning/blob/6cafba9f5bc5c67d2ba302d2f53082ef22685b42/lightning/src/offers/merkle.rs#L104 so it doesn't quite work. 
   
Just brainstorming here but... Would it be safer if the noHash option can only be taken on a particular piece of data that can be deserialized into a struct on LND's side? I suppose another option would be to support the full bolt 12 hash making process on LND's side instead.
   
   Oi, and sorry for the red X marks in the CI checks. I'll fix those up once we discuss what the best option is here. :)

2023-10-17 07:27 UTC, guggero commented
Ah, so it's just a tagged hash? I guess then instead of allowing the message not to be hashed, we could allow the `tag` to be set that should be used when hashing. Then we just need to disallow any specific BIP-340 tags (`"BIP0340/*"`) to avoid transaction hashes to be signed.

2023-10-20 20:15 UTC, orbitalturtle commented
@guggero Sorry for the slow reply, was making sure I can refactor to expose the tag data in LDK. Looks like it works so I'll rework this PR in that direction :)

2023-10-21 22:08 UTC, closed without merging

2023-10-21 22:27 UTC, orbitalturtle commented
Replacing this with a new PR to use a more accurate branch name.