Typo fix
lightningnetwork/lnd pull request #8236
Opened 2023-11-30 01:06 UTC by dplusplus1024

## Change Description
Description of change / link to associated issue.

## Steps to Test
Steps for reviewers to follow to test the change.

## Pull Request Checklist
### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

2023-11-30 01:07 UTC, ProofOfKeags approved these changes

2023-11-30 01:24 UTC, saubyk approved these changes
Ack

2023-11-30 09:08 UTC, yyforyongyu requested changes
As mentioned [here](https://github.com/lightningnetwork/lnd/pull/8237#pullrequestreview-1756961145), we need to run `make rpc`, and the commit message format needs to be fixed.

2023-12-07 09:36 UTC, lightninglabs-deploy commented
@dplusplus1024, remember to re-request review from reviewers when ready

2023-12-14 10:30 UTC, lightninglabs-deploy commented
@dplusplus1024, remember to re-request review from reviewers when ready

2023-12-21 11:18 UTC, lightninglabs-deploy commented
@dplusplus1024, remember to re-request review from reviewers when ready

2023-12-28 11:50 UTC, lightninglabs-deploy commented
@dplusplus1024, remember to re-request review from reviewers when ready

2024-01-04 11:51 UTC, lightninglabs-deploy commented
@dplusplus1024, remember to re-request review from reviewers when ready

2024-01-11 12:33 UTC, lightninglabs-deploy commented
@dplusplus1024, remember to re-request review from reviewers when ready

2024-01-12 01:01 UTC, ProofOfKeags commented
Replaced by #8375 due to inactivity from original author.

2024-01-12 01:01 UTC, closed without merging