Typo fix
lightningnetwork/lnd pull request #8237
Opened 2023-11-30 01:11 UTC by dplusplus1024

2023-11-30 01:26 UTC, saubyk approved these changes
lgtm

edit: @yyforyongyu's feedback needs to be addressed

2023-11-30 09:06 UTC, yyforyongyu requested changes
Please check the contribution guideline re how we write commit messages. Also `swagger.json` is auto-generated file, you need to modify the `proto` files first then run `make rpc`.

2023-12-14 10:30 UTC, lightninglabs-deploy commented
@saubyk: review reminder
@dplusplus1024, remember to re-request review from reviewers when ready

2023-12-21 11:18 UTC, lightninglabs-deploy commented
@saubyk: review reminder
@dplusplus1024, remember to re-request review from reviewers when ready

2023-12-28 11:50 UTC, lightninglabs-deploy commented
@saubyk: review reminder
@dplusplus1024, remember to re-request review from reviewers when ready

2024-01-04 11:51 UTC, lightninglabs-deploy commented
@saubyk: review reminder
@dplusplus1024, remember to re-request review from reviewers when ready

2024-01-11 12:33 UTC, lightninglabs-deploy commented
@saubyk: review reminder
@dplusplus1024, remember to re-request review from reviewers when ready

2024-01-12 08:28 UTC, guggero commented
Replaced by #8375.

2024-01-12 08:28 UTC, closed without merging