Update safety.md
lightningnetwork/lnd pull request #8724
Opened 2024-05-03 15:24 UTC by LeoSpyke

## Change Description
Remove dead conjoin implementations from docs.

## Steps to Test
Steps for reviewers to follow to test the change.

## Pull Request Checklist
### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

2024-05-08 07:53 UTC, ellemouton approved these changes
Thanks 🙏  a few nits

2024-05-08 07:53 UTC, ellemouton commented on docs/safety.md
>  1. Send all on-chain funds of the old node through a Coin Join service (like
while we are here, can we fix the s/Coin Join/CoinJoin typo? 🙏

2024-05-08 07:53 UTC, ellemouton commented on docs/safety.md
> +   Joinmarket) until a sufficiently high anonymity set is
s/Joinmarket/JoinMarket

2024-05-08 07:53 UTC, ellemouton commented on docs/safety.md
>     reached.
nit: this now fits on previous line

2024-05-09 02:42 UTC, saubyk requested changes
Recommend edit the entire sentence to below:
`If desired, take steps to preserve the onchain privacy of the funds from the old node`

Does not make sense to call out any specific method or service here

2024-05-16 03:11 UTC, lightninglabs-deploy commented
@leospyke, remember to re-request review from reviewers when ready

2024-05-23 03:59 UTC, lightninglabs-deploy commented
@leospyke, remember to re-request review from reviewers when ready

2024-05-30 04:41 UTC, lightninglabs-deploy commented
@leospyke, remember to re-request review from reviewers when ready

2024-06-06 05:29 UTC, lightninglabs-deploy commented
@leospyke, remember to re-request review from reviewers when ready

2024-06-13 06:22 UTC, lightninglabs-deploy commented
@leospyke, remember to re-request review from reviewers when ready

2024-06-20 07:15 UTC, lightninglabs-deploy commented
@leospyke, remember to re-request review from reviewers when ready

2024-06-21 22:47 UTC, saubyk commented
Hi @LeoSpyke can take over this pr, if you don't have availability to address the recommendations

2024-06-28 23:31 UTC, lightninglabs-deploy commented
@leospyke, remember to re-request review from reviewers when ready

2024-07-05 23:45 UTC, lightninglabs-deploy commented
@leospyke, remember to re-request review from reviewers when ready

2024-07-15 00:38 UTC, lightninglabs-deploy commented
@leospyke, remember to re-request review from reviewers when ready

2024-07-22 00:42 UTC, lightninglabs-deploy commented
@leospyke, remember to re-request review from reviewers when ready

2024-07-22 06:55 UTC, guggero commented
Replaced by https://github.com/lightningnetwork/lnd/pull/8925.

2024-07-22 06:55 UTC, closed without merging