Allow multiple etcd host
lightningnetwork/lnd pull request #8845
Opened 2024-06-16 21:27 UTC by bitbandi

## Change Description
This patch allow set multiple etcd servers. like an etcd cluster in docker swarm/kubernetes.

## Steps to Test
    ./lnd-debug \
       --db.backend=etcd \
       --db.etcd.host=etcd1:2379,etcd2:2379 \

## Pull Request Checklist
### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [ ]  [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our  [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

2024-06-17 05:22 UTC, yyforyongyu requested changes
Thank you for the PR!

Please refer to our contribution guidelines on how to [create commit messages](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#ideal-git-commit-structure).

This will also need a release note.

2024-06-17 09:24 UTC, bitbandi commented
Signed the commit. i dont know what to write to release note.

2024-06-20 09:28 UTC, guggero commented
Can be something simple, like "Allow multiple etcd hosts to be specified in `db.etcd.host`."
The important thing is that you link to this PR in the release notes, which makes that specific check in the CI green.

2024-06-27 09:52 UTC, lightninglabs-deploy commented
@bitbandi, remember to re-request review from reviewers when ready

2024-07-04 10:03 UTC, lightninglabs-deploy commented
@bitbandi, remember to re-request review from reviewers when ready

2024-07-11 10:34 UTC, lightninglabs-deploy commented
@bitbandi, remember to re-request review from reviewers when ready

2024-07-18 11:35 UTC, lightninglabs-deploy commented
@bitbandi, remember to re-request review from reviewers when ready

2024-07-22 11:59 UTC, guggero requested changes
Thanks for the PR!

The changes here are made in a Golang submodule (`kvdb`, see [go.mod](https://github.com/lightningnetwork/lnd/blob/84fd911b476240bf6d172b54e734e99e38520c8d/kvdb/go.mod)), which means this will need another PR that updates the submodule in the [main `go.mod`](https://github.com/lightningnetwork/lnd/blob/84fd911b476240bf6d172b54e734e99e38520c8d/go.mod) file. 
This can't be done in the same PR, mostly just FYI.

So this looks good to me once we update the configuration description (so users know this is a feature).

2024-07-22 11:59 UTC, guggero commented on kvdb/etcd/db.go
> +		Endpoints:          strings.Split(cfg.Host, ","),
I think we should also add something to the configuration description [here](https://github.com/lightningnetwork/lnd/blob/84fd911b476240bf6d172b54e734e99e38520c8d/kvdb/etcd/config.go#L17) and [here](https://github.com/lightningnetwork/lnd/blob/e8196c6feb0a7720c3e1f54deb46685f4651b311/sample-lnd.conf#L1377).

Perhaps something like `Etcd database host; supports multiple values separated by a comma`.

2024-07-29 12:33 UTC, lightninglabs-deploy commented
@bitbandi, remember to re-request review from reviewers when ready

2024-07-31 09:12 UTC, guggero approved these changes

2024-07-31 12:37 UTC, yyforyongyu approved these changes
LGTM, thanks for the fix!

2024-07-31 12:37 UTC, yyforyongyu commented on kvdb/etcd/config.go
> +	Host string `long:"host" description:"Etcd database host. Supports multiple hosts separated by a comma"`
nit: missing a period `.`

2024-07-31 12:37 UTC, yyforyongyu commented on docs/release-notes/release-notes-0.18.3.md
> +* [Allow](https://github.com/lightningnetwork/lnd/pull/8845) multiple etcd hosts
nit: missing a newline

2024-07-31 13:30 UTC, bitbandi commented on docs/release-notes/release-notes-0.18.3.md
> +* [Allow](https://github.com/lightningnetwork/lnd/pull/8845) multiple etcd hosts
fixed

2024-07-31 13:32 UTC, bitbandi commented
conflict resolved

2024-07-31 14:55 UTC, merged