[NANO]: Remove useless appendages from lnwallet/channel.go
lightningnetwork/lnd pull request #8979
Opened 2024-08-06 01:15 UTC by ProofOfKeags

## Change Description
gopls informed me that these parameters are not used and when I remove them, they are indeed not necessary.

## Steps to Test
make unit pkg=lnwallet

## Pull Request Checklist
### Testing
- [ ] Your PR passes all CI checks.
- [ ] Tests covering the positive and negative (error paths) are included.
- [ ] Bug fixes contain tests triggering the bug to prevent regressions.

### Code Style and Documentation
- [ ] The change obeys the [Code Documentation and Commenting](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#CodeDocumentation) guidelines, and lines wrap at 80.
- [ ] Commits follow the [Ideal Git Commit Structure](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md#IdealGitCommitStructure).
- [ ] Any new logging statements use an appropriate subsystem and logging level.
- [ ] Any new lncli commands have appropriate tags in the comments for the rpc in the proto file.
- [ ] [There is a change description in the release notes](https://github.com/lightningnetwork/lnd/tree/master/docs/release-notes), or `[skip ci]` in the commit message for small changes.

📝 Please see our [Contribution Guidelines](https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md) for further guidance.

2024-08-06 05:57 UTC, yyforyongyu requested changes
CI failed.

2024-08-06 05:57 UTC, yyforyongyu commented on lnwallet/channel.go
> -	chanID := lnwire.NewChanIDFromOutPoint(lc.channelState.FundingOutpoint)
looks like it's still been used below.

2024-08-06 06:06 UTC, ProofOfKeags commented
I got trigger happy with the commit reordering turns out the last commit needed to be part of a different series

2024-08-06 15:24 UTC, carlaKC approved these changes
935e7f1bee3a5d61bf80d5db1cd43bad48ecaea0 lgtm

2024-08-06 15:24 UTC, carlaKC commented on lnwallet/channel.go
>  	remoteCommitKeys *CommitmentKeyRing, whoseCommit lntypes.ChannelParty,
Unnecessary `*CommitmentKeyRing` after `localCommitKeys`, same for `extractPayDescs`

2024-08-06 17:27 UTC, yyforyongyu approved these changes
LGTM🦾

2024-08-06 20:01 UTC, carlaKC commented on lnwallet/channel.go
>  	remoteCommitKeys *CommitmentKeyRing, whoseCommit lntypes.ChannelParty,
feelz

<img width="454" alt="omsac" src="https://github.com/user-attachments/assets/22d4676e-66ac-4f60-9cf1-26919d75318c">

2024-08-07 02:11 UTC, ProofOfKeags commented
Failure is a flake. Send it.

2024-08-07 07:37 UTC, merged