(routing+lnrpc): arbitrary route source + route transformation
lightningnetwork/lnd pull request #9153
Opened 2024-10-03 03:29 UTC by calvinrzachman

## Background & Motivation

We'd like to allow a _**ChannelRouter**_ running _remotely_ from a set of _**lnd**_  instances to find paths through the network to payment destinations. For this, I have been able to come up with 2 choices:
1. Additional channel edges emanating from source representing fake/virtual channels: the remote _**ChannelRouter**_ can have its own sense of self and think itself connected to all **_lnd_** backends via virtual channel edges. In this scenario, the channel edges emanating from the source node exist only to facilitate tricking the path finding of the **_ChannelRouter_** that its self node is actually connected to the broader network. Concerning how the **_ChannelRouter_** and pathfinding are to be informed of these edges:
    1. The additional edges remain payment session/life-cycle [scoped](https://github.com/lightningnetwork/lnd/blob/v0.18.3-beta/routing/payment_session.go#L203). We could update the _**routerpc**_ RPC pre-processing step to mix a dynamically maintained set of edges in with every request. OR 
    2. Make the additional edges a dynamically configurable aspect of the [channel graph](https://github.com/lightningnetwork/lnd/blob/v0.18.3-beta/routing/graph.go#L28) that the **_ChannelRouter_** uses for pathfinding. NOTE: Currently trying this and it seems to work.

2. Delegated pathfinding: the remote _**ChannelRouter**_ has multiple personality disorder, taking its sense of “self” to be all of the **_lnd_** backend nodes. Then, during pathfinding, it would select as the pathfinding source a given backend.
    1. This sounds like a heavier lift from an **_lnd_** code change perspective. It also seems to imply the need for load balancing across which backends are selected for the delegation in a way that is not required with existing _**ChannelRouter**_ logic if the proxy's _**ChannelRouter**_ believes itself to be connected to each **_lnd_** backend via virtual channel edge.

## Change Description
**_If_** we use additional edges emanating from source node to trick the remote **_ChannelRouter_** into thinking that it’s connected to a set of **_lnd_** instances, then the routes/onions we build will include the **_lnd_** backend as a first hop. This presents us with a choice we can either:
1. Build routes/onions which include the **_lnd_** instance as the first hop. Implement **_SendOnion_** such that it peels the first onion layer before forwarding to outbound peer via the Switch.
2. Trim the first hop from the route/onion such that the first hop is the LN peer of the **_lnd_** instance. The **_SendOnion_** RPC does NOT need to peel the onion and can just forward it directly to the Switch/outbound peer.

The **_BuildRoute_** RPC provides a natural point to trim routes before sending them back to the client. Supporting the **_SendPaymentV2_** flow from the remote _**ChannelRouter**_ is a bit more involved as it does NOT have the ability to transform the route prior to onion construction and payment dispatch. We may need route post-processing hooks or otherwise more first class treatment of the channel edges emanating from source so that they meet our desired criteria. This is where the **_RouteTransformationFunc_** idea comes in.

- Allow configurable post-processing which transforms paths or routes built by the _**ChannelRouter**_. This allows a setup in which the _**ChannelRouter**_ runs remotely from the _**HTLCSwitch**_ to build routes as if they we're constructed from the perspective of the _**lnd**_ instance itself by trimming hops. This means that the onions the _**ChannelRouter**_ builds will be ready for direct delivery to the peer of an _**lnd**_ backend via the _**SendOnion**_ style RPC, without requiring it be peeled.
    - Could probably handle this on _**paymentLifecycle**_ level rather than _**paymentSession**_ as well 🤔 

The **_RouterBackend_** currently assumes that the source public key for a route is _always_ the node’s public key when calling **_UnmarshallRoute_**. This means that any reliance we have on **_SourcePubKey_** field is troubled as modifications (eg: trimming) by **_BuildRoute_** or **_QueryRoutes_** will be undone.

- Allow for marshal/unmarshal of route objects with arbitrary source public keys. This allows for setting the correct source public key when trimming hops representing traversal of such edges representing virtual channels. This allows the remote _**ChannelRouter**_ to avoid maintaining any new state and instead rely on its existing _**ControlTower**_ state to maintain a mapping from _**attempt_id**_ --> _**public key**_ of the _**lnd**_ backend which we delivered the onion to via _**SendOnion**_. This allows the remote _**ChannelRouter**_ to ultimately track the result of a given remote payment attempt via a _**TrackOnion**_ style RPC.

The _**BuildRoute**_ method relies on being given a continuous sequence of **_hop_** public keys from source to destination. The _**routerrpc.Server**_  and **_ChannelRouter_** currently assume that the source public key for a route is _always_ the node’s public key.

- Allow _**BuildRoute**_ to accept an optional override source public key. We will use the node's public key by default. This allows a remote _**ChannelRouter**_ to construct routes as if they we're built from the perspective of another node.

2024-10-14 07:08 UTC, lightninglabs-deploy commented
@ellemouton: review reminder

2024-10-21 07:22 UTC, lightninglabs-deploy commented
@ellemouton: review reminder

2024-10-21 10:34 UTC, ellemouton commented
## High level thoughts
thanks for the detailed outline. I guess I had initially thought we could have a new very abstract "virtual channel" type that the remote channel router could open with each of the LND nodes. Each LND node can be given an allow-list of who to accept such a channel from. If that abstraction could be possible, then the underlying method of sending should be able work as is today right? Ie channel router just builds the routes and sends directly to switch which uses UpdateAddHTLC to communicate the send. Then the LND node will see the incoming UpdateAddHTLC from an upstream virtual channel. 

Anyways - that is just what I thought the plan was. But perhaps getting channels to be that abstract is a bit of a tall order. 

## Re the PR description

> Supporting the SendPaymentV2 flow from the remote ChannelRouter is a bit more involved as it does NOT have the ability to transform the route prior to onion construction and payment dispatch

I think I lost you a bit at this point. are you saying that the remove router will call SendPayment on the LND nodes? I thought a new SendOnion endpoint was the idea? Or are you saying that the SendPayment is called on the channelrouter? If the former, then im not sure why the real LND node needs to transform the route?

Yeah I think I lost you after this point. It would help to have a step by step flow (ie, what is calling what when and what is doing what transformation when etc etc).

2024-10-21 11:11 UTC, ellemouton requested changes

2024-10-21 11:11 UTC, ellemouton commented on routing/router.go
> +type RouteTransformFunc func(route *route.Route) *route.Route
do we definitely want the flexibility to transform the entire route? It's a bit of a red flag to me cause we are depending on this module to construct a route but then we also as a caller are able to just replace that entire route... so can we not restrict the options a bit? Like `WithPeeledFirstNode` and things like that?

2024-10-21 11:11 UTC, ellemouton commented on lnrpc/lightning.proto
> +    string source_pub_key = 9;
can use `optional`

2024-10-21 11:11 UTC, ellemouton commented on lnrpc/routerrpc/router_backend.go
>  	prevNodePubKey := r.SelfNode
`prevNodePubKey` is not necessarily selfnode anymore

2024-10-21 11:11 UTC, ellemouton commented on lnrpc/routerrpc/router_backend.go
>  	prevNodePubKey := r.SelfNode
I think we should add tests for this change to make sure that things like this would be caught.

2024-10-21 11:11 UTC, ellemouton commented on lnrpc/routerrpc/router_backend.go
>  	prevNodePubKey := r.SelfNode
gotta make sure that everywhere where `r.SelfNode` is used is still correct given this commit

2024-10-21 11:11 UTC, ellemouton commented on routing/router.go
> +func (r *ChannelRouter) GetSelfNode() route.Vertex {
can just call it `SelfNode`. Getter is implied (unless it clashes with a member in ChannelRouter (which I dont think it does))

2024-10-21 11:11 UTC, ellemouton commented on docs/release-notes/release-notes-0.19.0.md
> +* [Allow arbitrary source public key for BuildRoute RPC](https://github.com/lightningnetwork/lnd/pull/9153) so that lnd's _*ChannelRouter*_ and _*routerrpc.Server*_ can build routes from the perspect
wrap at 80 🙏 
(while we are here, we can fix the wrapping of the entry above (for 9017) as well)

2024-10-28 11:57 UTC, lightninglabs-deploy commented
@calvinrzachman, remember to re-request review from reviewers when ready

2024-11-04 12:13 UTC, lightninglabs-deploy commented
@calvinrzachman, remember to re-request review from reviewers when ready

2024-11-18 13:07 UTC, lightninglabs-deploy commented
@calvinrzachman, remember to re-request review from reviewers when ready

2024-11-25 14:07 UTC, lightninglabs-deploy commented
@calvinrzachman, remember to re-request review from reviewers when ready

2024-12-02 15:03 UTC, lightninglabs-deploy commented
@calvinrzachman, remember to re-request review from reviewers when ready

2024-12-09 15:13 UTC, lightninglabs-deploy commented
@calvinrzachman, remember to re-request review from reviewers when ready

2024-12-23 16:08 UTC, lightninglabs-deploy commented
@calvinrzachman, remember to re-request review from reviewers when ready

2024-12-30 16:13 UTC, lightninglabs-deploy commented
@calvinrzachman, remember to re-request review from reviewers when ready

2025-01-06 16:24 UTC, lightninglabs-deploy commented
@calvinrzachman, remember to re-request review from reviewers when ready

2025-01-13 16:52 UTC, lightninglabs-deploy commented
@calvinrzachman, remember to re-request review from reviewers when ready

2025-01-20 17:01 UTC, lightninglabs-deploy commented
@calvinrzachman, remember to re-request review from reviewers when ready

2025-01-27 17:36 UTC, lightninglabs-deploy commented
@calvinrzachman, remember to re-request review from reviewers when ready

2025-02-03 18:43 UTC, lightninglabs-deploy commented
@calvinrzachman, remember to re-request review from reviewers when ready

2025-02-10 19:28 UTC, lightninglabs-deploy commented
@calvinrzachman, remember to re-request review from reviewers when ready

2025-02-11 05:46 UTC, yyforyongyu commented
!lightninglabs-deploy mute

2026-03-26 14:12 UTC, calvinrzachman commented on routing/payment_session.go
> +	routeTransform RouteTransformFunc
Updated `routeTransform` to `fn.Option[RouteTransformFunc]` on both `sessionOptions` and `SessionSource` ✅

2026-03-26 14:13 UTC, calvinrzachman commented on routing/payment_session.go
> +	}
added `sessionOptions` struct with `defaultSessionOptions()` constructor and `withRouteTransform` as a functional option.

2026-03-26 14:13 UTC, calvinrzachman commented on routing/payment_session_test.go
> +func TestRouteTransformFunc(t *testing.T) {
added a doc in here.

2026-03-26 14:14 UTC, calvinrzachman commented on routing/payment_session.go
> +	// A transformation which will be applied to every route created for
updated

2026-04-03 02:46 UTC, Roasbeef approved these changes
LGTM 🍠

2026-04-03 02:46 UTC, Roasbeef commented on routing/payment_session.go
> +		p.opts.routeTransform.WhenSome(
I think the point brought up below (why can't the caller transform it themselves?) may still be relevant. Still getting through the diff.

2026-04-03 02:46 UTC, Roasbeef commented on routing/payment_session.go
> +		p.opts.routeTransform.WhenSome(
On second thought, the payment session has awareness of this as it's the one that's constructing the route in the first place. The caller typically makes the session, then exits (eg: one time payment send), so it would need _some_ lower level hook somewhere in the process.

2026-04-22 14:44 UTC, calvinrzachman commented on routing/payment_session.go
> +		p.opts.routeTransform.WhenSome(
Yeah, for the `QueryRoutes/BuildRoute` --> `SendToRouteV2` flow where an external RPC client obtains the route from _**lnd**_ there is ample opportunity for the client to manipulate the route however they desire. The `routerrpc.SendPaymentV2` handles the path-finding, onion construction, dispatch, etc. all internally and so and external RPC client has no opportunity to manipulate the route. The lower level hook helps out with this. Though notably, I think this design (https://github.com/lightningnetwork/lnd/pull/10764) obviates the need for any route transform hooks. If it's deemed suitable - it also simplifies the the client side implementation no longer requiring the addition of additional edges on the source side to the underlying channel graph used by the router.

2026-04-30 18:36 UTC, merged