lnwire+netann: update structure of g175 messages to be pure TLV
lightningnetwork/lnd pull request #9175
Opened 2024-10-11 14:42 UTC by ellemouton

Update the structure of all gossip 1.75 messages to be purely TLV. 
With this update, the signature is also a TLV record. There is a un-signed 
and signed range of TLVs. The signature along with things like SPV proofs
will fall in the un-signed range. 
I've used the same un-signed range used by Bolt12 messages. 

This PR introduces a new `PureTLVMessage` interface for messages like this
and adds a comprehensive test to ensure that old clients (who are aware of
fewer fields of a message than new clients) and new clients still generate the 
same correct digest of a message regardless of if they are aware of all the 
records or not.

2024-10-16 11:26 UTC, ellemouton commented
Ok i've also now updated this PR to include validating the signature of a 
ChannelAnnouncement2 message for the case where it is announcing a P2WSH channel.

2024-10-16 22:57 UTC, Roasbeef requested changes

2024-10-16 22:57 UTC, Roasbeef commented on go.mod
> +replace github.com/lightningnetwork/lnd/tlv => github.com/ellemouton/lnd/tlv v0.0.0-20241012094556-298ff9eaed58
I think we can remove this now?

2024-10-16 22:57 UTC, Roasbeef commented on lnwire/pure_tlv.go
> +	pureTLVUnsignedRangeOneStart  = 160
Should have `godoc` comments.

2024-10-16 22:57 UTC, Roasbeef commented on lnwire/pure_tlv.go
> +	pureTLVUnsignedRangeTwoStart  = 3000000000
How did we arrive at these values?

2024-10-16 22:57 UTC, Roasbeef commented on lnwire/pure_tlv.go
> +func SerialiseFieldsToSign(msg PureTLVMessage) ([]byte, error) {
We might want to adopt a similar structure for the signed portion of the dyn commit messages @ProofOfKeags. Basically we copied over from the way BOLT 12 works, and we can use the TLV type values, then let this handle how serialization works (does require a message to be pure TLV).

2024-10-16 22:57 UTC, Roasbeef commented on lnwire/pure_tlv.go
> +	pureTLVUnsignedRangeTwoStart  = 3000000000
Also I think we should try to capture this in the spec, independent of G 1.75.

2024-10-16 22:57 UTC, Roasbeef commented on lnwire/pure_tlv_test.go
> +	ExtraFieldsInSignedRange map[uint64][]byte
Should something like this be split out into an embeddable struct?

2024-10-16 22:57 UTC, Roasbeef commented on lnwire/channel_announcement_2.go
> -	ExtraOpaqueData ExtraOpaqueData
Why won't we need this field any longer? What about the field we don't know about in the unsigned range?

2024-10-16 22:57 UTC, Roasbeef commented on lnwire/announcement_signatures_2.go
> +	ExtraFieldsInSignedRange map[uint64][]byte
Also why can't we just continue to store it in the serialized form?

2024-10-16 22:57 UTC, Roasbeef commented on discovery/gossiper.go
> +	chainHash *chainhash.Hash
Why do we need it here if we have `ChainParams`?

2024-10-16 22:57 UTC, Roasbeef commented on discovery/gossiper.go
> +	ChainParams *chaincfg.Params
I think this can be a normal value rather than a pointer.

2024-10-16 22:57 UTC, Roasbeef commented on discovery/gossiper.go
> +	pkScript, err := lnwallet.FetchPKScriptWithQuit(
What about the merkle proof case?

2024-10-16 22:57 UTC, Roasbeef commented on netann/channel_announcement.go
> +type FetchPkScript func(*lnwire.ShortChannelID) (txscript.ScriptClass,
Does the arg here need to be a pointer?

2024-10-23 22:57 UTC, lightninglabs-deploy commented
@ellemouton, remember to re-request review from reviewers when ready

2024-10-30 23:24 UTC, lightninglabs-deploy commented
@ellemouton, remember to re-request review from reviewers when ready

2024-11-06 23:37 UTC, lightninglabs-deploy commented
@ellemouton, remember to re-request review from reviewers when ready

2024-11-14 00:27 UTC, lightninglabs-deploy commented
@ellemouton, remember to re-request review from reviewers when ready

2024-11-21 00:46 UTC, lightninglabs-deploy commented
@ellemouton, remember to re-request review from reviewers when ready

2024-11-28 01:39 UTC, lightninglabs-deploy commented
@ellemouton, remember to re-request review from reviewers when ready

2024-12-09 10:56 UTC, lightninglabs-deploy commented
@ellemouton, remember to re-request review from reviewers when ready

2024-12-16 11:25 UTC, lightninglabs-deploy commented
@ellemouton, remember to re-request review from reviewers when ready

2024-12-23 11:51 UTC, lightninglabs-deploy commented
@ellemouton, remember to re-request review from reviewers when ready

2024-12-30 11:56 UTC, lightninglabs-deploy commented
@ellemouton, remember to re-request review from reviewers when ready

2025-01-06 12:09 UTC, lightninglabs-deploy commented
@ellemouton, remember to re-request review from reviewers when ready

2025-01-13 12:37 UTC, lightninglabs-deploy commented
@ellemouton, remember to re-request review from reviewers when ready

2025-01-14 01:46 UTC, Roasbeef commented
This ready for review again (review wasn't re-requested in UI).

2025-01-14 01:52 UTC, Roasbeef commented on netann/channel_announcement.go
> +type FetchPkScript func(*lnwire.ShortChannelID) (txscript.ScriptClass,
Moreso wondering what the behavior is if a nil chan ID is passed in. I assume it's just an error? In which case we can just accept the value, thereby eliminating an error flow.

2025-01-14 01:53 UTC, Roasbeef approved these changes
LGTM 🧜‍♂️

2025-02-01 07:40 UTC, ellemouton commented on discovery/gossiper.go
> +	chainHash *chainhash.Hash
removed 👍

2025-02-01 07:40 UTC, ellemouton commented on netann/channel_announcement.go
> +type FetchPkScript func(*lnwire.ShortChannelID) (txscript.ScriptClass,
cool - updated to be pass-by-value 👍

2025-08-04 09:16 UTC, ellemouton commented
TODO: add hard-code bytes test as suggested in:

https://github.com/lightningnetwork/lnd/pull/10072#issuecomment-3149750303

2025-09-15 10:44 UTC, litbot-9000 commented
@yyforyongyu: review reminder

2025-09-15 13:18 UTC, yyforyongyu approved these changes
LGTM🚢

2025-09-15 13:18 UTC, yyforyongyu commented on lnwallet/interface.go
> +	chanID lnwire.ShortChannelID) (*wire.MsgTx, error) {
👍

2025-09-15 13:18 UTC, yyforyongyu commented on lnwire/pure_tlv.go
> +	pureTLVSignedSecondRangeStart = 1000000000
Q: any particular reason that this range is chosen?

2025-09-15 13:18 UTC, yyforyongyu commented on lnwire/channel_announcement_2.go
> +//nolint:ll
nit: could name it `nonSigRecordProducers`?

2025-09-22 08:04 UTC, ellemouton commented on lnwire/pure_tlv.go
> +	pureTLVSignedSecondRangeStart = 1000000000
purely copying from the Bolt12 spec (ie using the same range defined there) & im not too sure if there was a specific reason for this range 🤷‍♀️

2025-09-22 08:04 UTC, ellemouton commented on lnwire/channel_announcement_2.go
> +//nolint:ll
cool yes will do 👍 

Opening a follow up PR to this one later today so will do this in first commit there 🫡

2025-09-22 08:04 UTC, merged